In [1]:
import zipfile
import os

# Define the path for the uploaded zip file and the extraction target directory
zip_path = r'C:\Users\prakh\OneDrive\Desktop\Project\heart+disease.zip'
extract_to = r'C:\Users\prakh\OneDrive\Desktop\heart_disease_data'

# Create a directory to extract to
os.makedirs(extract_to, exist_ok=True)

# Unzipping the file
with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_to)

# List the files in the extracted directory
extracted_files = os.listdir(extract_to)
extracted_files

['ask-detrano',
 'bak',
 'cleve.mod',
 'cleveland.data',
 'costs',
 'heart-disease.names',
 'hungarian.data',
 'Index',
 'long-beach-va.data',
 'new.data',
 'processed.cleveland.data',
 'processed.hungarian.data',
 'processed.switzerland.data',
 'processed.va.data',
 'reprocessed.hungarian.data',
 'switzerland.data',
 'WARNING']

In [2]:
# Path to the .names file
names_file_path = os.path.join(extract_to, 'heart-disease.names')

# Reading the content of the .names file
with open(names_file_path, 'r') as file:
    names_content = file.readlines()

names_content[:30]  # Displaying the first 30 lines to get an overview

['Publication Request: \n',
 '   >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>\n',
 '   This file describes the contents of the heart-disease directory.\n',
 '\n',
 '   This directory contains 4 databases concerning heart disease diagnosis.\n',
 '   All attributes are numeric-valued.  The data was collected from the\n',
 '   four following locations:\n',
 '\n',
 '     1. Cleveland Clinic Foundation (cleveland.data)\n',
 '     2. Hungarian Institute of Cardiology, Budapest (hungarian.data)\n',
 '     3. V.A. Medical Center, Long Beach, CA (long-beach-va.data)\n',
 '     4. University Hospital, Zurich, Switzerland (switzerland.data)\n',
 '\n',
 '   Each database has the same instance format.  While the databases have 76\n',
 "   raw attributes, only 14 of them are actually used.  Thus I've taken the\n",
 '   liberty of making 2 copies of each database: one with all the attributes\n',
 '   and 1 with the 14 attributes actually used in past experiments.\n',
 '\n',
 '   The authors of the databases have requested:\n',
 '\n',
 '      ...that any publications resulting from the use of the data include the \n',
 '      names of the principal investigator responsible for the data collection\n',
 '      at each institution.  They would be:\n',
 '\n',
 '       1. Hungarian Institute of Cardiology. Budapest: Andras Janosi, M.D.\n',
 '       2. University Hospital, Zurich, Switzerland: William Steinbrunn, M.D.\n',
 '       3. University Hospital, Basel, Switzerland: Matthias Pfisterer, M.D.\n',
 '       4. V.A. Medical Center, Long Beach and Cleveland Clinic Foundation:\n',
 '\t  Robert Detrano, M.D., Ph.D.\n',
 '\n']

In [3]:
import pandas as pd

# Path to the processed Cleveland dataset
cleveland_data_path = os.path.join(extract_to, 'processed.cleveland.data')

# Load the dataset, assuming a common format of comma-separated values without a header
# Based on typical structure of such files, defining names of the columns from provided data description
column_names = [
    "age", "sex", "cp", "trestbps", "chol", "fbs", "restecg",
    "thalach", "exang", "oldpeak", "slope", "ca", "thal", "num"
]

# Read the dataset into a DataFrame
cleveland_data = pd.read_csv(cleveland_data_path, names=column_names, na_values="?")

# Display the first few rows of the dataset
cleveland_data.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,num
0,63.0,1.0,1.0,145.0,233.0,1.0,2.0,150.0,0.0,2.3,3.0,0.0,6.0,0
1,67.0,1.0,4.0,160.0,286.0,0.0,2.0,108.0,1.0,1.5,2.0,3.0,3.0,2
2,67.0,1.0,4.0,120.0,229.0,0.0,2.0,129.0,1.0,2.6,2.0,2.0,7.0,1
3,37.0,1.0,3.0,130.0,250.0,0.0,0.0,187.0,0.0,3.5,3.0,0.0,3.0,0
4,41.0,0.0,2.0,130.0,204.0,0.0,2.0,172.0,0.0,1.4,1.0,0.0,3.0,0

In [4]:
# Define the path where you want to save the Excel file
excel_file_path = r'C:\Users\prakh\OneDrive\Desktop\Project\cleveland_data.xlsx'

# Export the DataFrame to an Excel file
cleveland_data.to_excel(excel_file_path, index=False)